# import necessary libraries

In [22]:
#!pip install mlxtend 
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

### import Dataset

In [3]:
online_retail_data = pd.read_excel("Online Retail.xlsx")
online_retail_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [ ]:
#pd.set_option("max_rows",None)

### data understanding

In [4]:
 online_retail_data.shape

(541909, 8)

In [6]:
online_retail_data.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [7]:
online_retail_data.describe(include="all")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909.0,541909,540455,541909.000000,541909,541909.000000,406829.000000,541909
unique,25900.0,4070,4223,NaN,NaN,NaN,NaN,38
top,573585.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom
freq,1114.0,2313,2369,NaN,NaN,NaN,NaN,495478
mean,NaN,NaN,NaN,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570,NaN
min,NaN,NaN,NaN,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,2011-03-28 11:34:00,1.250000,13953.000000,NaN
50%,NaN,NaN,NaN,3.000000,2011-07-19 17:17:00,2.080000,15152.000000,NaN
75%,NaN,NaN,NaN,10.000000,2011-10-19 11:27:00,4.130000,16791.000000,NaN
max,NaN,NaN,NaN,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000,NaN
std,NaN,NaN,NaN,218.081158,NaN,96.759853,1713.600303,NaN

In [8]:
online_retail_data["Country"].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [9]:
online_retail_data["Country"].nunique()

38

In [12]:
online_retail_data["Country"].value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

### lets build best associates for uk as it has more transcation

In [15]:
uk_data = online_retail_data[online_retail_data["Country"]=="United Kingdom"]
uk_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09 12:31:00,1.95,15804.0,United Kingdom
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09 12:49:00,2.95,13113.0,United Kingdom
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09 12:49:00,1.25,13113.0,United Kingdom
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,13113.0,United Kingdom
541893,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,13113.0,United Kingdom

In [ ]:
## No need to find integellient file here

#### 4. Data Mining

In [16]:
uk_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09 12:31:00,1.95,15804.0,United Kingdom
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09 12:49:00,2.95,13113.0,United Kingdom
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09 12:49:00,1.25,13113.0,United Kingdom
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,13113.0,United Kingdom
541893,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,13113.0,United Kingdom

In [18]:
uk_data.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133600
Country             0
dtype: int64

In [19]:
1454/495478

0.002934539979575279

In [20]:
del uk_data["CustomerID"]

In [23]:
uk_data.dropna(inplace = True)

In [24]:
uk_data.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
Country        0
dtype: int64

In [33]:
uk_pivotted_data = pd.pivot_table(data=uk_data,values="Quantity",index="InvoiceNo",columns="Description",aggfunc="sum").fillna(0)
uk_pivotted_data

Description,20713,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,wrongly coded 20713,wrongly coded 23343,wrongly coded-23343,wrongly marked,wrongly marked 23343,wrongly marked carton 22804,wrongly marked. 23343 in box,wrongly sold (22719) barcode,wrongly sold as sets,wrongly sold sets
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536366,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536367,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536368,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536369,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C581484,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C581490,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C581499,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C581568,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C581569,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### check southarbica

In [28]:
s_a_data = online_retail_data[online_retail_data["Country"]=="Saudi Arabia"]
s_a_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
100810,544838,22915,ASSORTED BOTTLE TOP MAGNETS,12,2011-02-24 10:34:00,0.42,12565.0,Saudi Arabia
100811,544838,22363,GLASS JAR MARMALADE,6,2011-02-24 10:34:00,2.95,12565.0,Saudi Arabia
100812,544838,22362,GLASS JAR PEACOCK BATH SALTS,6,2011-02-24 10:34:00,2.95,12565.0,Saudi Arabia
100813,544838,22361,GLASS JAR DAISY FRESH COTTON WOOL,6,2011-02-24 10:34:00,2.95,12565.0,Saudi Arabia
100814,544838,22553,PLASTERS IN TIN SKULLS,12,2011-02-24 10:34:00,1.65,12565.0,Saudi Arabia
100815,544838,22555,PLASTERS IN TIN STRONGMAN,12,2011-02-24 10:34:00,1.65,12565.0,Saudi Arabia
100816,544838,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-02-24 10:34:00,1.65,12565.0,Saudi Arabia
100817,544838,20781,GOLD EAR MUFF HEADPHONES,2,2011-02-24 10:34:00,5.49,12565.0,Saudi Arabia
100818,544838,22969,HOMEMADE JAM SCENTED CANDLES,12,2011-02-24 10:34:00,1.45,12565.0,Saudi Arabia
108127,C545507,22361,GLASS JAR DAISY FRESH COTTON WOOL,-5,2011-03-03 11:43:00,2.95,12565.0,Saudi Arabia

In [29]:
s_a_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
100810,544838,22915,ASSORTED BOTTLE TOP MAGNETS,12,2011-02-24 10:34:00,0.42,12565.0,Saudi Arabia
100811,544838,22363,GLASS JAR MARMALADE,6,2011-02-24 10:34:00,2.95,12565.0,Saudi Arabia
100812,544838,22362,GLASS JAR PEACOCK BATH SALTS,6,2011-02-24 10:34:00,2.95,12565.0,Saudi Arabia
100813,544838,22361,GLASS JAR DAISY FRESH COTTON WOOL,6,2011-02-24 10:34:00,2.95,12565.0,Saudi Arabia
100814,544838,22553,PLASTERS IN TIN SKULLS,12,2011-02-24 10:34:00,1.65,12565.0,Saudi Arabia
100815,544838,22555,PLASTERS IN TIN STRONGMAN,12,2011-02-24 10:34:00,1.65,12565.0,Saudi Arabia
100816,544838,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-02-24 10:34:00,1.65,12565.0,Saudi Arabia
100817,544838,20781,GOLD EAR MUFF HEADPHONES,2,2011-02-24 10:34:00,5.49,12565.0,Saudi Arabia
100818,544838,22969,HOMEMADE JAM SCENTED CANDLES,12,2011-02-24 10:34:00,1.45,12565.0,Saudi Arabia
108127,C545507,22361,GLASS JAR DAISY FRESH COTTON WOOL,-5,2011-03-03 11:43:00,2.95,12565.0,Saudi Arabia

In [47]:
s_a_pivotted_data= pd.pivot_table(data=s_a_data,values="Quantity",index="InvoiceNo",columns="Description",aggfunc="sum").fillna(0)
s_a_pivotted_data

Description,ASSORTED BOTTLE TOP MAGNETS,GLASS JAR DAISY FRESH COTTON WOOL,GLASS JAR MARMALADE,GLASS JAR PEACOCK BATH SALTS,GOLD EAR MUFF HEADPHONES,HOMEMADE JAM SCENTED CANDLES,PLASTERS IN TIN CIRCUS PARADE,PLASTERS IN TIN SKULLS,PLASTERS IN TIN STRONGMAN
InvoiceNo,,,,,,,,,
544838,12.0,6.0,6.0,6.0,2.0,12.0,12.0,12.0,12.0
C545507,0.0,-5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
s_a_pivotted_onehott=s_a_pivotted_data.applymap(lambda x:0 if x==0 else 1)
s_a_pivotted_onehott

Description,ASSORTED BOTTLE TOP MAGNETS,GLASS JAR DAISY FRESH COTTON WOOL,GLASS JAR MARMALADE,GLASS JAR PEACOCK BATH SALTS,GOLD EAR MUFF HEADPHONES,HOMEMADE JAM SCENTED CANDLES,PLASTERS IN TIN CIRCUS PARADE,PLASTERS IN TIN SKULLS,PLASTERS IN TIN STRONGMAN
InvoiceNo,,,,,,,,,
544838,1,1,1,1,1,1,1,1,1
C545507,0,1,0,0,0,0,0,0,0

In [50]:
from mlxtend.frequent_patterns import apriori,association_rules

In [53]:
frequent_itemsets_s_a = apriori(df = s_a_pivotted_onehott , min_support=0.02,use_colnames=True,)
frequent_itemsets_s_a

     support                                           itemsets
0        0.5                    (ASSORTED BOTTLE TOP  MAGNETS )
1        1.0                (GLASS JAR DAISY FRESH COTTON WOOL)
2        0.5                             (GLASS JAR MARMALADE )
3        0.5                     (GLASS JAR PEACOCK BATH SALTS)
4        0.5                         (GOLD EAR MUFF HEADPHONES)
..       ...                                                ...
506      0.5  (GLASS JAR MARMALADE , PLASTERS IN TIN CIRCUS ...
507      0.5  (PLASTERS IN TIN CIRCUS PARADE , GLASS JAR DAI...
508      0.5  (GLASS JAR MARMALADE , PLASTERS IN TIN CIRCUS ...
509      0.5  (GLASS JAR MARMALADE , PLASTERS IN TIN CIRCUS ...
510      0.5  (GLASS JAR MARMALADE , PLASTERS IN TIN CIRCUS ...

[511 rows x 2 columns]

In [54]:
best_associates_s_a = association_rules(df=frequent_itemsets_s_a,metric='confidence',min_threshold=0.02)
best_associates_s_a

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(ASSORTED BOTTLE TOP MAGNETS ),(GLASS JAR DAISY FRESH COTTON WOOL),0.5,1.0,0.5,1.0,1.0,1.0,0.00,inf,0.0,0.5,0.0,0.75
1,(GLASS JAR DAISY FRESH COTTON WOOL),(ASSORTED BOTTLE TOP MAGNETS ),1.0,0.5,0.5,0.5,1.0,1.0,0.00,1.0,0.0,0.5,0.0,0.75
2,(ASSORTED BOTTLE TOP MAGNETS ),(GLASS JAR MARMALADE ),0.5,0.5,0.5,1.0,2.0,1.0,0.25,inf,1.0,1.0,1.0,1.00
3,(GLASS JAR MARMALADE ),(ASSORTED BOTTLE TOP MAGNETS ),0.5,0.5,0.5,1.0,2.0,1.0,0.25,inf,1.0,1.0,1.0,1.00
4,(ASSORTED BOTTLE TOP MAGNETS ),(GLASS JAR PEACOCK BATH SALTS),0.5,0.5,0.5,1.0,2.0,1.0,0.25,inf,1.0,1.0,1.0,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18655,(ASSORTED BOTTLE TOP MAGNETS ),"(GLASS JAR MARMALADE , PLASTERS IN TIN CIRCUS ...",0.5,0.5,0.5,1.0,2.0,1.0,0.25,inf,1.0,1.0,1.0,1.00
18656,(PLASTERS IN TIN STRONGMAN),"(GLASS JAR MARMALADE , PLASTERS IN TIN CIRCUS ...",0.5,0.5,0.5,1.0,2.0,1.0,0.25,inf,1.0,1.0,1.0,1.00
18657,(HOMEMADE JAM SCENTED CANDLES),"(GLASS JAR MARMALADE , PLASTERS IN TIN CIRCUS ...",0.5,0.5,0.5,1.0,2.0,1.0,0.25,inf,1.0,1.0,1.0,1.00
18658,(GLASS JAR PEACOCK BATH SALTS),"(GLASS JAR MARMALADE , PLASTERS IN TIN CIRCUS ...",0.5,0.5,0.5,1.0,2.0,1.0,0.25,inf,1.0,1.0,1.0,1.00
18659,(GOLD EAR MUFF HEADPHONES),"(GLASS JAR MARMALADE , PLASTERS IN TIN CIRCUS ...",0.5,0.5,0.5,1.0,2.0,1.0,0.25,inf,1.0,1.0,1.0,1.00

In [55]:
best_associates_s_a.to_csv("best_antecedent_consequent_s_a.csv")

### uk dataseta

In [34]:
uk_pivotted_onehot= uk_pivotted_data.applymap(lambda x:0 if x==0 else 1)
uk_pivotted_onehot

Description,20713,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,wrongly coded 20713,wrongly coded 23343,wrongly coded-23343,wrongly marked,wrongly marked 23343,wrongly marked carton 22804,wrongly marked. 23343 in box,wrongly sold (22719) barcode,wrongly sold as sets,wrongly sold sets
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536366,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536368,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536369,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C581484,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C581490,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C581499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C581568,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C581569,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### data mining

In [35]:
from mlxtend.frequent_patterns import apriori,association_rules

In [42]:
frequent_itemsets = apriori(df=uk_pivotted_onehot, min_support=0.02,use_colnames=True)
frequent_itemsets

      support                                           itemsets
0    0.038884                           (6 RIBBONS RUSTIC CHARM)
1    0.026497                  (60 CAKE CASES VINTAGE CHRISTMAS)
2    0.034483                      (60 TEATIME FAIRY CAKE CASES)
3    0.025363                   (72 SWEETHEART FAIRY CAKE CASES)
4    0.040563                       (ALARM CLOCK BAKELIKE GREEN)
..        ...                                                ...
242  0.021461  (WHITE HANGING HEART T-LIGHT HOLDER, RED HANGI...
243  0.020962  (STRAWBERRY CHARLOTTE BAG, RED RETROSPOT CHARL...
244  0.020962  (ROSES REGENCY TEACUP AND SAUCER , REGENCY CAK...
245  0.024183  (WOODEN FRAME ANTIQUE WHITE , WOODEN PICTURE F...
246  0.022550  (GREEN REGENCY TEACUP AND SAUCER, PINK REGENCY...

[247 rows x 2 columns]

In [45]:
best_associates = association_rules(df=frequent_itemsets,metric='confidence',min_threshold=0.02)
best_associates

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED ),0.040563,0.043512,0.025817,0.636465,14.627420,1.0,0.024052,2.631078,0.971022,0.443146,0.619928,0.614896
1,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE GREEN),0.043512,0.040563,0.025817,0.593326,14.627420,1.0,0.024052,2.359232,0.974016,0.443146,0.576133,0.614896
2,(CHARLOTTE BAG PINK POLKADOT),(RED RETROSPOT CHARLOTTE BAG),0.031352,0.041697,0.021915,0.698987,16.763518,1.0,0.020607,3.183593,0.970783,0.428571,0.685890,0.612279
3,(RED RETROSPOT CHARLOTTE BAG),(CHARLOTTE BAG PINK POLKADOT),0.041697,0.031352,0.021915,0.525571,16.763518,1.0,0.020607,2.041714,0.981262,0.428571,0.510216,0.612279
4,(CHARLOTTE BAG SUKI DESIGN),(RED RETROSPOT CHARLOTTE BAG),0.036933,0.041697,0.021688,0.587224,14.083142,1.0,0.020148,2.321603,0.964619,0.380876,0.569263,0.553677
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,"(GREEN REGENCY TEACUP AND SAUCER, ROSES REGENC...",(PINK REGENCY TEACUP AND SAUCER),0.032350,0.033303,0.022550,0.697055,20.930634,1.0,0.021473,3.190995,0.984058,0.523158,0.686618,0.687083
86,"(PINK REGENCY TEACUP AND SAUCER, ROSES REGENCY...",(GREEN REGENCY TEACUP AND SAUCER),0.025272,0.044011,0.022550,0.892280,20.274075,1.0,0.021438,8.874766,0.975325,0.482524,0.887321,0.702326
87,(GREEN REGENCY TEACUP AND SAUCER),"(PINK REGENCY TEACUP AND SAUCER, ROSES REGENCY...",0.044011,0.025272,0.022550,0.512371,20.274075,1.0,0.021438,1.998913,0.994442,0.482524,0.499728,0.702326
88,(PINK REGENCY TEACUP AND SAUCER),"(GREEN REGENCY TEACUP AND SAUCER, ROSES REGENC...",0.033303,0.032350,0.022550,0.677112,20.930634,1.0,0.021473,2.996856,0.985028,0.523158,0.666317,0.687083
89,(ROSES REGENCY TEACUP AND SAUCER ),"(GREEN REGENCY TEACUP AND SAUCER, PINK REGENCY...",0.045508,0.026543,0.022550,0.495513,18.668575,1.0,0.021342,1.929600,0.991558,0.455545,0.481758,0.672543

In [46]:
best_associates.to_csv("best_antecedent_consequent.csv")